### ISSUE TITLE
unhappy flow

### ISSUE THREAD

**Issue by 030** [030/nexus3-cli#6]
go run main.go

results in:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x65a198]

goroutine 1 [running]:
nexus3-cli/cli.continuationToken(0x6ed79f, 0x4, 0x0, 0x0)
        /home/ben/dev/nexus3-cli/cli/cli.go:35 +0x198
nexus3-cli/cli.ContinuationTokenRecursion(0x6ed79f, 0x4, 0x0, 0xc0000a9f40, 0x40712f)
        /home/ben/dev/nexus3-cli/cli/cli.go:63 +0x39
main.downloadURLs()
        /home/ben/dev/nexus3-cli/main.go:14 +0x48
main.main()
        /home/ben/dev/nexus3-cli/main.go:77 +0x20
exit status 2
```

if nexus is not running. The suggestion is to return a clear error message.

**Comment by 030** [comment]
continuationTokenRecursion should be validated. It is either null or UUID

**Comment by 030** [comment]
https://medium.com/@nate510/don-t-use-go-s-default-http-client-4804cb19f779
> var netClient = &http.Client{
>   Timeout: time.Second * 10,
> }
> 
> response, _ := netClient.Get(url)
